# === MusicBrainz2Notion Settings === #
[musicbrainz2notion]
artists_to_update = []

# === API keys === #
# notion_api_key = "secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# fanart_api_key = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# === Database IDs: Uncomment === #
# artist_db_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# release_db_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
# track_db_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# === Release filters === #
release_type_filter = ["album", "ep"]
release_secondary_type_exclude = ["compilation", "live"]

# === Misc === #
min_nb_tags = 3
cover_size = 500
force_update_canonical_data = false
add_track_thumbnail = true


[musicbrainz2notion-global]
# === Icon emojis === #
ARTIST_ICON = "🧑‍🎤"
RELEASE_ICON = "💽"
TRACK_ICON = "🎼"

# === Select Placeholders === #
EMPTY_TYPE_PLACEHOLDER = "Unknown"
EMPTY_AREA_PLACEHOLDER = "Unknown"
EMPTY_LANGUAGE_PLACEHOLDER = "Unknown"

# === Other === #
REQUEST_TIMEOUT = 10
