# === MusicBrainz2Notion Settings === #
[musicbrainz2notion]
artists_to_update = []

# === API keys === #
# notion_api_key = "secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# fanart_api_key = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# === Database IDs: Uncomment === #
# artist_db_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# release_db_id = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"
# track_db_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# === Release filters === #
release_type_filter = ["album", "ep"]
release_status_filter = ["official"]
release_secondary_type_exclude = ["compilation", "live"]

# === Icon emojis === #
artist_icon = "🧑‍🎤"
release_icon = "💽"
track_icon = "🎼"


# === Misc === #
min_nb_tags = 3
force_update_canonical_data = false
add_track_thumbnail = true


# === Adanced === #
thumbnail_size = 500
request_timeout = 10

empty_type_placeholder = "Unknown"
empty_area_placeholder = "Unknown"
empty_language_placeholder = "Unknown"
